spring.application.name=codexa-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/codexa
spring.datasource.username=postgres
spring.datasource.password=Sriram13@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true